server:
  port: 62105
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/advanced_web?useUnicode=true&charsetEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
jwtconfig:
  secret: lomer
  timeout: 3600000
timesetting:
  sessiontimeout: 10000 # 10 seconds todo : change it to 10000